// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgPksUP3MZ9gX-baZSyXiMIg07wWwjGOA',
    appId: '1:466922201959:web:16451317926646aec305c2',
    messagingSenderId: '466922201959',
    projectId: 'paragon-hq',
    authDomain: 'paragon-hq.firebaseapp.com',
    storageBucket: 'paragon-hq.firebasestorage.app',
    measurementId: 'G-C8P5YSTQ38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo_tPkVHhnVVi6v6plD85I9wHjk12McC0',
    appId: '1:466922201959:android:066784517759a489c305c2',
    messagingSenderId: '466922201959',
    projectId: 'paragon-hq',
    storageBucket: 'paragon-hq.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNZY8LOnfaUMUzpUIAhetcdoIozydgzWY',
    appId: '1:466922201959:ios:6805785538357736c305c2',
    messagingSenderId: '466922201959',
    projectId: 'paragon-hq',
    storageBucket: 'paragon-hq.firebasestorage.app',
    iosBundleId: 'com.example.paragon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgPksUP3MZ9gX-baZSyXiMIg07wWwjGOA',
    appId: '1:466922201959:web:b2de0bfaef5ea1a1c305c2',
    messagingSenderId: '466922201959',
    projectId: 'paragon-hq',
    authDomain: 'paragon-hq.firebaseapp.com',
    storageBucket: 'paragon-hq.firebasestorage.app',
    measurementId: 'G-9DEQCRW0YH',
  );
}
